/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as RouteRouteImport } from './routes/Route'
import { Route as NetworkRouteRouteImport } from './routes/network/route'
import { Route as IndexRouteImport } from './routes/index'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RouteRoute = RouteRouteImport.update({
  id: '/Route',
  path: '/Route',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRouteRoute = NetworkRouteRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/network': typeof NetworkRouteRoute
  '/Route': typeof RouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/network': typeof NetworkRouteRoute
  '/Route': typeof RouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/network': typeof NetworkRouteRoute
  '/Route': typeof RouteRoute
  '/_layout': typeof LayoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/network' | '/Route'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/network' | '/Route'
  id: '__root__' | '/' | '/network' | '/Route' | '/_layout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NetworkRouteRoute: typeof NetworkRouteRoute
  RouteRoute: typeof RouteRoute
  LayoutRoute: typeof LayoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Route': {
      id: '/Route'
      path: '/Route'
      fullPath: '/Route'
      preLoaderRoute: typeof RouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NetworkRouteRoute: NetworkRouteRoute,
  RouteRoute: RouteRoute,
  LayoutRoute: LayoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
