services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_LOG_LEVEL=debug
    ports:
      - "3030:3000"
    volumes:
      - "grafana-storage:/var/lib/grafana"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_DB=center
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

volumes:
  prometheus-data:
  grafana-storage:
  postgres_data:
